# Generated by Django 4.2.4 on 2023-08-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenitiy', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'property_amenities',
            },
        ),
        migrations.CreateModel(
            name='Propertybasicinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=50)),
                ('can_sleep_max', models.IntegerField(null=True)),
                ('floor', models.IntegerField(null=True)),
                ('size', models.FloatField(null=True)),
                ('street', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('detailed_location', models.FloatField(null=True)),
                ('detailed_location_id', models.IntegerField(null=True)),
                ('license_number', models.CharField(max_length=50)),
                ('license_toggle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rental_properties_app.amenities')),
            ],
            options={
                'db_table': 'property_basic_info',
            },
        ),
        migrations.CreateModel(
            name='Propertyprices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50, null=True)),
                ('date_from', models.DateTimeField(null=True)),
                ('date_to', models.DateTimeField(null=True)),
                ('no_of_guests', models.IntegerField(null=True)),
                ('daily_price', models.FloatField(null=True)),
                ('min_stay', models.IntegerField(null=True)),
                ('extra_guest_price', models.FloatField(null=True)),
                ('propertyinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_properties_app.propertybasicinfo')),
            ],
            options={
                'db_table': 'property_prices',
            },
        ),
        migrations.CreateModel(
            name='Propertyimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('image_type', models.CharField(max_length=50)),
                ('image_descriptions', models.JSONField()),
                ('propertyinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_properties_app.propertybasicinfo')),
            ],
            options={
                'db_table': 'property_images',
            },
        ),
        migrations.CreateModel(
            name='Propertydescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('propertyinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_properties_app.propertybasicinfo')),
            ],
            options={
                'db_table': 'property_description',
            },
        ),
        migrations.CreateModel(
            name='Propertycheckincheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_name', models.CharField(max_length=50)),
                ('prior_days', models.IntegerField(default=0)),
                ('landlord_email', models.EmailField(max_length=254, null=True)),
                ('landlord_telephone', models.CharField(max_length=50, null=True)),
                ('checkin_time_from', models.CharField(default='00:00', max_length=50)),
                ('checkin_time_to', models.CharField(default='00:00', max_length=50)),
                ('checkout_time', models.CharField(default='00:00', max_length=50)),
                ('checkinplace', models.CharField(default='at_the_apartment', max_length=50)),
                ('fee_type', models.CharField(max_length=50, null=True)),
                ('fee_from', models.CharField(default='00:00', max_length=50)),
                ('fee_to', models.CharField(default='00:00', max_length=50)),
                ('fee_cost', models.FloatField(default=0)),
                ('propertyinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_properties_app.propertybasicinfo')),
            ],
            options={
                'db_table': 'property_checkin_checkout',
            },
        ),
        migrations.CreateModel(
            name='Propertycharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, null=True)),
                ('calculation_type', models.CharField(max_length=50, null=True)),
                ('collection_time', models.CharField(max_length=50, null=True)),
                ('value', models.FloatField(null=True)),
                ('is_optional', models.BooleanField(default=0)),
                ('down_payment_type', models.CharField(max_length=50, null=True)),
                ('down_payment_amount', models.FloatField(null=True)),
                ('security_deposit_type', models.CharField(max_length=50, null=True)),
                ('security_deposit_amount', models.FloatField(null=True)),
                ('propertyinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_properties_app.propertybasicinfo')),
            ],
            options={
                'db_table': 'property_charges',
            },
        ),
        migrations.CreateModel(
            name='Propertyavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(null=True)),
                ('date_to', models.DateTimeField(null=True)),
                ('no_of_units', models.IntegerField(null=True)),
                ('changeover', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('is_price', models.BooleanField(default=False)),
                ('daily_price', models.FloatField(null=True)),
                ('min_stay', models.IntegerField(null=True)),
                ('extra_guest_price', models.FloatField(null=True)),
                ('season', models.CharField(max_length=50, null=True)),
                ('propertyinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_properties_app.propertybasicinfo')),
            ],
            options={
                'db_table': 'property_availability',
            },
        ),
    ]
