# Generated by Django 4.2.4 on 2023-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybasicinfo',
            name='license_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertybasicinfo',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertycheckincheckout',
            name='landlord_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertydescription',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image_descriptions',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
