# Generated by Django 4.2.4 on 2023-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0002_alter_propertybasicinfo_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='amenity_id',
            field=models.IntegerField(null=True),
        ),
    ]
