# Generated by Django 4.2.4 on 2023-08-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0003_amenities_amenity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='amenitiy',
            new_name='amenity',
        ),
    ]
