# Generated by Django 4.2.4 on 2023-08-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0005_alter_amenities_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybasicinfo',
            name='amenities',
        ),
        migrations.AddField(
            model_name='amenities',
            name='property_id',
            field=models.TextField(null=True),
        ),
    ]
