# Generated by Django 4.2.4 on 2023-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0006_remove_propertybasicinfo_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybasicinfo',
            name='property_id',
            field=models.IntegerField(null=True),
        ),
    ]
