# Generated by Django 4.2.4 on 2023-08-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0007_propertybasicinfo_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyavailability',
            name='changeover',
        ),
        migrations.RemoveField(
            model_name='propertyavailability',
            name='no_of_units',
        ),
        migrations.RemoveField(
            model_name='propertyprices',
            name='min_stay',
        ),
    ]
