# Generated by Django 4.2.4 on 2023-08-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0008_remove_propertyavailability_changeover_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propertyavailability',
            new_name='Propertyavailabilityprices',
        ),
        migrations.AlterModelTable(
            name='propertyavailabilityprices',
            table='property_availability_prices',
        ),
        migrations.DeleteModel(
            name='Propertyprices',
        ),
    ]
