# Generated by Django 4.2.4 on 2023-08-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0009_rename_propertyavailability_propertyavailabilityprices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertycheckincheckout',
            old_name='fee_type',
            new_name='early_departure_fee',
        ),
        migrations.RenameField(
            model_name='propertycheckincheckout',
            old_name='fee_cost',
            new_name='early_departure_fee_cost',
        ),
        migrations.RenameField(
            model_name='propertycheckincheckout',
            old_name='fee_from',
            new_name='early_departure_fee_from',
        ),
        migrations.RenameField(
            model_name='propertycheckincheckout',
            old_name='fee_to',
            new_name='early_departure_fee_to',
        ),
        migrations.AddField(
            model_name='propertycheckincheckout',
            name='late_arrival_fee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertycheckincheckout',
            name='late_arrival_fee_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='propertycheckincheckout',
            name='late_arrival_fee_from',
            field=models.CharField(default='00:00', max_length=50),
        ),
        migrations.AddField(
            model_name='propertycheckincheckout',
            name='late_arrival_fee_to',
            field=models.CharField(default='00:00', max_length=50),
        ),
    ]
