# Generated by Django 4.2.4 on 2023-08-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0010_rename_fee_type_propertycheckincheckout_early_departure_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycheckincheckout',
            name='early_departure_fee',
        ),
        migrations.RemoveField(
            model_name='propertycheckincheckout',
            name='late_arrival_fee',
        ),
    ]
