# Generated by Django 4.2.4 on 2023-08-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0012_propertycharges_applied_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycharges',
            name='calculation_type',
        ),
        migrations.RemoveField(
            model_name='propertycharges',
            name='collection_time',
        ),
        migrations.RemoveField(
            model_name='propertycharges',
            name='down_payment_type',
        ),
        migrations.RemoveField(
            model_name='propertycharges',
            name='extra_charge_type',
        ),
        migrations.RemoveField(
            model_name='propertycharges',
            name='security_deposit_type',
        ),
        migrations.AddField(
            model_name='propertycharges',
            name='calculation_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertycharges',
            name='collection_time_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertycharges',
            name='down_payment_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertycharges',
            name='extra_charge_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertycharges',
            name='security_deposit_type_id',
            field=models.IntegerField(null=True),
        ),
    ]
