# Generated by Django 4.2.4 on 2023-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0013_remove_propertycharges_calculation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimages',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
