# Generated by Django 4.2.4 on 2023-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0014_propertyimages_language_alter_propertyimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybasicinfo',
            name='group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertybasicinfo',
            name='property_rental_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='propertybasicinfo',
            name='property_rental_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
