# Generated by Django 4.2.4 on 2023-08-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0015_propertybasicinfo_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionRoooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition_room', models.CharField(max_length=255)),
                ('composition_id', models.IntegerField(null=True)),
                ('property_id', models.TextField(null=True)),
            ],
            options={
                'db_table': 'composition_rooms',
            },
        ),
    ]
