# Generated by Django 4.2.4 on 2023-08-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0017_alter_compositionroooms_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompositionRoooms',
            new_name='CompositionRooms',
        ),
    ]
