# Generated by Django 4.2.4 on 2023-08-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_properties_app', '0018_rename_compositionroooms_compositionrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images'),
        ),
    ]
